# The purpose of this Antora playbook is to generate a preview of the docs in the current branch.
antora:
  extensions:
  - '@antora/collector-extension'
site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: docs
    worktrees: true
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
urls:
  latest_version_segment: ''
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
